source 'https://rubygems.org'

group :test do
  gem 'rake', '>= 10.1.1'
  gem 'puppet', '= 3.1.1'
  gem 'facter', '= 1.6.18'
  gem 'rspec', '~> 2.99.0'
  gem 'rspec-puppet', '>= 2.0.1'
  gem 'puppetlabs_spec_helper', '>= 0.8.1'
  gem 'metadata-json-lint'
  gem 'rspec-puppet-facts'
end
